# Generated by Django 5.1.3 on 2024-11-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('position', models.CharField(max_length=80)),
                ('bat_thr', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
