# Generated by Django 5.1.3 on 2024-11-21 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0002_alter_player_bat_thr_alter_player_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
    ]
